"use client";

import { ResultsData } from "@/app/types";
import EngineerCard from "./EngineerCard";
import MethodologySection from "./MethodologySection";

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export default function Dashboard({ data }: { data: ResultsData }) {
  const { metadata, methodology, engineers } = data;
  const top5 = engineers.slice(0, 5);

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <header className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <svg className="w-8 h-8 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
            </svg>
            <h1 className="text-2xl font-bold tracking-tight">Engineering Impact Dashboard</h1>
          </div>
          <p className="text-gray-400 text-sm">
            Top contributors at PostHog for{" "}
            <span className="text-gray-300 font-medium">
              {formatDate(metadata.period.start)} &ndash; {formatDate(metadata.period.end)}
            </span>
          </p>

          {/* Stats bar */}
          <div className="flex flex-wrap gap-4 mt-4">
            <MetaStat label="PRs Analyzed" value={metadata.total_prs_analyzed.toLocaleString()} />
            <MetaStat label="Engineers" value={metadata.total_engineers.toString()} />
            <MetaStat label="Model" value={metadata.model_used} />
            <MetaStat
              label="Generated"
              value={new Date(metadata.generated_at).toLocaleDateString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
                hour: "2-digit",
                minute: "2-digit",
              })}
            />
          </div>
        </header>

        {/* Pillar legend */}
        <div className="flex flex-wrap gap-x-5 gap-y-1 mb-5 text-xs text-gray-500">
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-blue-500 inline-block" />
            Contribution (40%)
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-purple-500 inline-block" />
            Review (25%)
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 inline-block" />
            Velocity (20%)
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-orange-500 inline-block" />
            Breadth (15%)
          </span>
        </div>

        {/* Engineer cards */}
        <div className="space-y-3 mb-8">
          {top5.map((engineer) => (
            <EngineerCard key={engineer.login} engineer={engineer} />
          ))}
        </div>

        {/* Methodology */}
        <MethodologySection methodology={methodology} />

        {/* Footer */}
        <footer className="mt-8 pt-4 border-t border-gray-800/60 text-center text-xs text-gray-600">
          Scores generated by AI analysis. Click any card for details.
        </footer>
      </div>
    </div>
  );
}

function MetaStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center gap-1.5 text-sm">
      <span className="text-gray-500">{label}:</span>
      <span className="text-gray-300 font-medium">{value}</span>
    </div>
  );
}
